config/routes.rb
ServihogarRails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations", sessions: "user/sessions"}
  devise_for :providers, :controllers => {:registrations => "provider/registrations", sessions: "provider/sessions"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :provider_attachments, only: [:create, :destroy]

  resources :referrals

  root 'providers#home'
  get 'bookings/booking_resume/:booking_id' => 'bookings#booking_resume', as: 'booking_resume'
  get 'bookings/send_mail/:provider_id/:booking_id' => 'bookings#send_mail'
  get 'meetings/send_mail/:provider_id/:meeting_id' => 'meetings#send_mail'
  get 'providers/update_state' => 'providers#update_state'
  

  resources :providers do
    collection do      
       get 'create_info' 
    end  
  end    

  resources :users

  resources :pets
  resources :bookings

  post 'bookings/new' => 'bookings#new'

  resources :meetings

  resources :comments

  resources :favorites

  get 'beneficios' => 'providers#benefits'
  get 'promo' => 'providers#promo'

  namespace :api, defaults: { format: 'json' } do
    get 'providers/get_providers' => 'providers#get_providers', as: 'api_get_providers'
    get 'providers/get_session_params' => 'providers#get_session_params', as: 'api_get_session_params'
    get 'bookings/get_new_booking' => 'providers#get_new_booking', as: 'api_get_new_booking'

    post 'bookings/get_rate' => 'bookings#get_rate'
    get 'bookings/get_rate' => 'bookings#get_rate'

    post 'bookings/get_pet_rate' => 'bookings#get_pet_rate', as: 'get_pet_rate'
    

    get 'services/get_services' => 'services#get_services', as: 'api_get_services'
    get 'general/get_sizes' => 'general#get_sizes', as: 'api_get_sizes'
  end

  resources :categories, only: [:show]

  get 'pages/tc' => 'high_voltage/pages#show', id: 'tc'

  get 'la' => 'providers#la_home', as: 'la_home'

end

app/models/referral.rb
# == Schema Information
#
# Table name: referrals
#
#  id             :integer          not null, primary key
#  code_value     :string(255)
#  referrer_name  :string(255)
#  referrer_email :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Referral < ActiveRecord::Base
	validates_presence_of :referrer_email, :referrer_name
	validates_format_of :referrer_email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates_uniqueness_of :referrer_email
	include TokenableReferral
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  before_action :set_referral, only: [:show, :destroy]

  # GET /referrals
  # GET /referrals.json
  def index
    @referrals = Referral.all
  end

  # GET /referrals/1
  # GET /referrals/1.json
  def show
  end

  # GET /referrals/new
  def new
    @referral = Referral.new
  end

  # POST /referrals
  # POST /referrals.json
  def create
    @referral = Referral.new(referral_params)

    respond_to do |format|
      if @referral.save
        session[:code_id] = @referral.id
        format.html { redirect_to @referral, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @referral }
        format.js { render action: 'show', status: :created, location: @referral }
      else
        format.html { render action: 'new' }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
        format.js { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1
  # DELETE /referrals/1.json
  def destroy
    @referral.destroy
    respond_to do |format|
      format.html { redirect_to referrals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referral
      @referral = Referral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referral_params
      params.require(:referral).permit(:code_value, :referrer_name, :referrer_email)
    end
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@referral, remote: remote, html: {role: :form, 'data-model' => 'referral'}) do |f| %>

  <% if @referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
      <% @referral.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
      <%= f.label "Nombre:", class: 'control-label light h4 pull-left' %><br>
    <%= f.text_field :referrer_name, class: 'form-control' %>
    <span class="help-block"></span>
  </div>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
      <%= f.label "Correo electronico:", class: 'control-label light h4 pull-left' %><br>
    <%= f.text_field :referrer_email, class: 'form-control' %>
    <span class="help-block"></span>
  </div>

  <%# Added Bootstrap classes %>
  <div class="actions">
    <%= f.submit 'Generar código', :id => "btn-recomendar" , class: 'btn btn-default', :onClick=>"_gaq.push(['_trackEvent', 'Modal', 'Generar-codigo']);"  %>
  </div>

<% end %>

app/views/referrals/_table_row.html.erb
<div class="row p-14">
  <div class="col-sm-2"><%= referral.code_value %></div>
  <div class="col-sm-2"><%= referral.referrer_name %></div>
  <div class="col-sm-2"><%= referral.referrer_email %></div>
</div>

app/views/referrals/edit.html.erb
<h1>Editing referral</h1>

<%= render 'form' %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<h1>Listing referrals</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Referrer name</th>
      <th>Referrer email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.code %></td>
        <td><%= referral.referrer_name %></td>
        <td><%= referral.referrer_email %></td>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>

app/views/referrals/new.html.erb
<h1>New referral</h1>

<%= render 'form' %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/new.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-heading');
$modalHeading.html("PRUEBA");
$modalBody.html("ssgsd");
$modal.modal();

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @referral.code %>
</p>

<p>
  <strong>Referrer name:</strong>
  <%= @referral.referrer_name %>
</p>

<p>
  <strong>Referrer email:</strong>
  <%= @referral.referrer_email %>
</p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/show.js.erb
$('#referrals_table').html("<%= j render partial: 'table_row', locals: {referral: @referral } %>");
// $('#new_code_modal').removeClass('hidden');
$('#new_code_modal').modal_success();