config/routes.rb
ServihogarRails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations", sessions: "user/sessions"}
  devise_for :providers, :controllers => {:registrations => "provider/registrations", sessions: "provider/sessions"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :provider_attachments, only: [:create, :destroy]

  resources :referrals

  root 'providers#home'
  get 'bookings/booking_resume/:booking_id' => 'bookings#booking_resume', as: 'booking_resume'
  get 'bookings/send_mail/:provider_id/:booking_id' => 'bookings#send_mail'
  get 'meetings/send_mail/:provider_id/:meeting_id' => 'meetings#send_mail'
  get 'providers/update_state' => 'providers#update_state'
  

  resources :providers do
    collection do      
       get 'create_info' 
    end  
  end    

  resources :users

  resources :pets
  resources :bookings

  post 'bookings/new' => 'bookings#new'

  resources :meetings

  resources :comments

  resources :favorites

  get 'beneficios' => 'providers#benefits'
  get 'promo' => 'providers#promo'

  namespace :api, defaults: { format: 'json' } do
    get 'providers/get_providers' => 'providers#get_providers', as: 'api_get_providers'
    get 'providers/get_session_params' => 'providers#get_session_params', as: 'api_get_session_params'
    get 'bookings/get_new_booking' => 'providers#get_new_booking', as: 'api_get_new_booking'

    post 'bookings/get_rate' => 'bookings#get_rate'
    get 'bookings/get_rate' => 'bookings#get_rate'

    post 'bookings/get_pet_rate' => 'bookings#get_pet_rate', as: 'get_pet_rate'
    

    get 'services/get_services' => 'services#get_services', as: 'api_get_services'
    get 'general/get_sizes' => 'general#get_sizes', as: 'api_get_sizes'
  end

  resources :categories, only: [:show]

  get 'pages/tc' => 'high_voltage/pages#show', id: 'tc'

  get 'la' => 'providers#la_home', as: 'la_home'

end

app/views/layouts/partial/_comments.haml
- provider.comments.each do |comment|
  .comment-container.row
    .user-avatar.col-xs-2.hidden-phone
      =image_tag(comment.user.photo, width: '50px', height: '50px', class: 'img-circle')
    .comment-body.col-xs-10
      %h4= "#{comment.user.first_name} #{comment.user.last_name}"
      .valorations.row
        - comment.comment_valuations.each do |cval|
          .col-md-3.col-xs-6
            %b=cval.valuation.name
            .ratingStars.mt-7{el: "this", score: cval.value.to_i, readOnly: true}
      .comment-text.row.mt-21
        .col-xs-12
          %p= comment.body
  %hr
%p
  %b Deja una calificación y un comentario sobre tu cuidador
%br
- if current_user != nil
  - @comment = Comment.new
  = simple_nested_form_for(@comment, :html => {:multipart => true}, remote: true) do |f|
    .row.valorations-row
      - Valuation.all.each do |valuation|
        .col-md-3.col-mx-6
          %b=valuation.name
          .ratingStars{el: "#val_#{valuation.id}", score:'0'}
          %input{name:"comment[comment_valuations_attributes][#{valuation.id}][valuation_id]", value: valuation.id, type: 'hidden'}
          %input{name:"comment[comment_valuations_attributes][#{valuation.id}][value]", id:"val_#{valuation.id}"}

    .new_comment.row.mt-21
      .avatar.col-md-2
        = image_tag(current_user.photo, width: '50px', height: '50px', class: 'img-circle')
      .comment.col-md-8
        =f.input :provider_id, input_html: {value: provider.id}, as: :hidden
        =f.input :body, label: false
      .col-md-2.mt-7
        = f.submit "Comentar", class: 'btn btn-primary'
- else
  %p Registrate o ingresa con tu cuenta para poder dejar un comentario

app/views/layouts/partial/_footer.html.erb
<div id="footer" class="mt-70-mob">  
  <section class="bg-success pt-21 pb-21">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-xs-12 pt-7">
          <h5 class="text-white text-footer">Contáctanos: </h5>
            <% current_country.phone.split("/").each do |el|%>
              <h5 class="text-white text-footer"><%= el %></h5>
            <% end %>
        </div>
        <div class="col-md-2 col-xs-12"> 
          <div class="row pt-7">
            <div class="col-md-12 footer-links">
              <h5 class="text-white text-footer"> Síguenos en </h5>
              <a href="<%= current_country.facebook  %>" target="_blank">
                <%= image_tag('facebook.svg')%>
              </a>
              <a href="<%= current_country.twitter %>" target="_blank">
                <%= image_tag('twitter.svg')%>
              </a>
              <a href="https://instagram.com/kmimosmx/" target="_blank">
                <%= image_tag('instagram.svg')%>
              </a>  
            </div>
          </div>
        </div>
        <div class="col-md-2 url-link">
            <a href="http://www.kmimos.com.mx"><h5 class="text-white text-footer"> www.kmimos.com.mx </h5></a>
            <a href="http://www.kmimos.la"><h5 class="text-white text-footer"> www.kmimos.la </h5></a>
        </div>
        <div class="col-md-4 text-muted text-right col-xs-12">
          <h5 class="text-footer">Todos los derechos reservados</h5>
            <a href="http://eepurl.com/bFnq55" target="_blank" class="newsletter">Suscríbete a nuestro newsletter</a>
            <%= link_to '<h5>Términos y condiciones</h5>'.html_safe, page_path('tc'), class: "text-footer" %>
        </div>
      </div>
    </div>
  </section>
</div>
<script>
  $(window).load(function() {
    // The slider being synced must be initialized first
    $('#carousel').flexslider({
      animation: "slide",
      controlNav: false,
      animationLoop: false,
      slideshow: false,
      itemWidth: 120,
      itemMargin: 5,
      asNavFor: '#slider'
    });

    $('#slider').flexslider({
      animation: "slide",
      controlNav: false,
      animationLoop: false,
      slideshow: false,
      sync: "#carousel"
    });
  });
</script>

<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0022/5945.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
<!-- crazyegg begins -->
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0029/3661.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
<!-- crazyegg ends -->

app/views/layouts/partial/_header.haml
.navbar.internal
  .navbar-header
    %button.navbar-toggle.mt-28.c-menu{"data-target" => ".navbar-collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .p-7.hidden-xs.hidden-sm.col-xs-4= link_to image_tag('logo-kmimos.svg', class: "mt--14 img-logo"), root_url
    .p-7.hidden-xs.hidden-sm.col-xs-4
      = link_to image_tag('booking.svg', class: "pt-7 mt-14 ml-28 img-home", style: "width: 250px"), "http://www.booking.com/index.html?aid=1147066", target: '_blank'

    .p-7.hidden-md.hidden-lg.col-xs-4
      = link_to image_tag('logo-kmimos.svg', class: "mt-0 img-logo"), root_url      
      = link_to image_tag('booking.svg', class: "", style: "width: 200px; padding: 0px; padding-left: 10px;"), "http://www.booking.com/index.html?aid=1147066", target: '_blank'
    
      

    - if current_user
      %ul.nav.navbar-nav.mt-7.ml-56.hidden-xs
        %li= link_to 'Mi Perfil', user_path(current_user), class: "not-underline white-text"
        %li= link_to 'Mis Reservas', bookings_path, class: "not-underline white-text"
  .collapse.navbar-collapse.text-center
    %div.text-center.hidden-lg.hidden-md
    - if current_provider
      .hidden-lg.hidden-md.hidden
        %li.block.h2= link_to 'Mi perfil', edit_provider_path(current_provider.id)
        %li.block.h2= link_to 'Salir', destroy_provider_session_path, :method => :delete   
    - elsif current_user
      .hidden-lg.hidden-md.hidden
        %li.block.h2= link_to 'Mi perfil', user_path(current_user)
        %li.block.h2= link_to 'Mis Reservas', bookings_path
        %li.block.h2= link_to 'Salir', destroy_user_session_path, :method => :delete 
    - else
      .hidden-lg.hidden-md.hidden
        %li.block.h2= link_to 'Iniciar sesión como Cliente', new_user_session_path, class:'not-underline text-header'
        %li.block.h2= link_to 'Iniciar sesión como Cuidador', new_provider_session_path, class:'not-underline text-header'
        %li.block.h2.pb-21= link_to 'Regístrate', new_user_registration_path, class: "not-underline text-header"
        %li.block.h2= link_to 'Quiero ser cuidador', new_provider_registration_path, class: " sign-up"

    %ul.nav.navbar-nav.mt-14.hidden-xs
      - if current_provider
        %li.ml-35
          .dropdown 
            %a.dropdown-toggle.text-header{"data-toggle" => "dropdown", :href => "#"}
              Hola, #{current_provider.name}
            %ul#dropdown-menu.dropdown-menu
              %li.block= link_to 'Editar perfil', edit_provider_path(current_provider.id)
              %li.block= link_to 'Salir', destroy_provider_session_path, :method => :delete   
      - elsif current_user
        %li.ml-35
          .dropdown 
            %a.dropdown-toggle.text-header{"data-toggle" => "dropdown", :href => "#"}
              Hola, #{current_user.first_name}
            %ul#dropdown-menu.dropdown-menu
              %li{:style => "display:block;"}= link_to 'Mi perfil', user_path(current_user)
              %li{:style => "display:block;"}= link_to 'Mis reservas', bookings_path 
              %li{:style => "display:block;"}= link_to 'Salir', destroy_user_session_path, :method => :delete 
           
      - else
        %li
          .dropdown
            %a.dropdown-toggle.text-header.btn.pv-7(data-toggle="dropdown")
              %span.h5.book.pr-14.ls-md Iniciar Sesión
              %span.caret
            %ul(class="dropdown-menu")
              %li 
                %a{:href => new_user_session_path} Iniciar sesión como Cliente
              %li 
                %a{:href => new_provider_session_path} Iniciar sesión como Cuidador 
        %li= link_to 'Registrarme', new_user_registration_path, class: "not-underline text-header"
        %li.active= link_to 'Quiero ser cuidador', new_provider_registration_path, class: "not-underline sign-up"

app/views/layouts/partial/_initializer.haml
// Google Analytics

- if Rails.env.production?
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-56422840-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      // ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    

// Start of Zopim Live Chat Script
   
    
:javascript
  window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
  d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
  _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
  $.src='//v2.zopim.com/?2rAZA158tdPofy3mBWtUwxr1sLuiKHRl';z.t=+new Date;$.
  type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
  
  
   
   
 
  

app/views/layouts/partial/_metas.haml
%meta{:charset => "utf-8"}/
%meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
%meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1", :name => "viewport"}/
/ Project SEO
%meta{:content => "", :name => "description"}/
%meta{:content => "", :name => "keywords"}/
%meta{:content => "", :name => "author"}/
/ Responsiveness
%meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/
/ Open Graph
%meta{:content => "website", :property => "og:type"}/
%meta{:content => "http://www.kmimos.la", :property => "og:url"}/
%meta{:content => "Kmimos", :property => "og:title"}/
%meta{:content => "Kmimos", :property => "og:site_name"}/
%meta{:content => "Conéctate con gente de confianza para consentir a tu mascota como se merece.", :property => "og:description"}/
%meta{:content => "http://s22.postimg.org/deqqkyzi9/perro2.png", :property => "og:image"}/
/ Twitter Cards
%meta{:content => "", :name => "twitter:card"}/
%meta{:content => "", :name => "twitter:title"}/
%meta{:content => "", :name => "twitter:url"}/
%meta{:content => "", :name => "twitter:description"}/
%meta{:content => "", :name => "twitter:site"}/
%meta{:content => "", :name => "twitter:creator"}/
%meta{:content => "", :name => "twitter:image"}/

app/views/layouts/partial/_mix_panel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("77809472a7285576b84c47460cd1c826");</script><!-- end Mixpanel -->
  
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0039/9228.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

<!-- Start Visual Website Optimizer Synchronous Code -->
<script type='text/javascript'>
var _vis_opt_account_id = 222949;
var _vis_opt_protocol = (('https:' == document.location.protocol) ? 'https://' : 'http://');
document.write('<s' + 'cript src="' + _vis_opt_protocol +
'dev.visualwebsiteoptimizer.com/deploy/js_visitor_settings.php?v=1&a='+_vis_opt_account_id+'&url='
+encodeURIComponent(document.URL)+'&random='+Math.random()+'" type="text/javascript">' + '<\/s' + 'cript>');
</script>

<script type='text/javascript'>
if(typeof(_vis_opt_settings_loaded) == "boolean") { document.write('<s' + 'cript src="' + _vis_opt_protocol +
'd5phz18u4wuww.cloudfront.net/vis_opt.js" type="text/javascript">' + '<\/s' + 'cript>'); }
// if your site already has jQuery 1.4.2, replace vis_opt.js with vis_opt_no_jquery.js above
</script>

<script type='text/javascript'>
if(typeof(_vis_opt_settings_loaded) == "boolean" && typeof(_vis_opt_top_initialize) == "function") {
        _vis_opt_top_initialize(); vwo_$(document).ready(function() { _vis_opt_bottom_initialize(); });
}
</script>
<!-- End Visual Website Optimizer Synchronous Code -->

<!-- Google Code para etiquetas de remarketing -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 881017978;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/881017978/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/layouts/partial/_mobile_header.haml
- if current_user
  %h2= link_to 'Mi Perfil', user_path(current_user), class: "not-underline white-text"
  %h2= link_to 'Mis Reservas', bookings_path, class: "not-underline white-text"
  %h2= link_to 'Salir', destroy_provider_session_path, :method => :delete  
- elsif current_provider
  %h2= link_to 'Actualizar mi perfil'.html_safe, edit_provider_path(current_provider), class: "not-underline white-text"
  %h2= link_to 'Salir'.html_safe, destroy_provider_session_path, :method => :delete 
- else
  %h2= link_to 'Iniciar sesión como Cliente', new_user_session_path, class:'not-underline text-header'
  %h2= link_to 'Iniciar sesión como Cuidador', new_provider_session_path, class:'not-underline text-header'
  %h2= link_to 'Regístrate', new_user_registration_path, class: "not-underline text-header"
  %h2= link_to 'Quiero ser cuidador', new_provider_registration_path, class: "not-underline sign-up"
    

app/views/layouts/partial/_new_header.haml
%header.site-menu
  #menu-vistas.vistas.hidden-xs.container-fluid.text-center
    .header-center.col-md-6.text-right.pull-right
      .collapse.navbar-collapse.pr-21
        %ul.nav.navbar-nav.mt-14
          - if current_provider
            %li
              .dropdown 
                %a.dropdown-toggle.text-header.btn.pv-7(data-toggle="dropdown")
                  Hola, #{current_provider.name}
                %ul#dropdown-menu.dropdown-menu
                  %li= link_to 'Actualizar mi perfil'.html_safe, edit_provider_path(current_provider) 
                  %li= link_to 'Salir'.html_safe, destroy_provider_session_path, :method => :delete 
          - elsif current_user
            %li
              .dropdown 
                %a.dropdown-toggle.text-header.btn.pv-7(data-toggle="dropdown")
                  %span.h5.book.pr-14.ls-md Hola, #{current_user.first_name }
                %ul.dropdown-menu
                  %li{:style => "display:block;"}= link_to 'Mi perfil'.html_safe, user_path(current_user) 
                  %li{:style => "display:block;"}= link_to 'Mis Reservas'.html_safe, bookings_path 
                  %li{:style => "display:block;"}= link_to 'Salir'.html_safe, destroy_user_session_path, :method => :delete 
          - else
            %li
              .dropdown
                %a.dropdown-toggle.text-header.btn.pv-7(data-toggle="dropdown")
                  %span.h5.book.pr-14.ls-md Iniciar Sesión
                  %span.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => new_user_session_path}
                      %span.h5.btn Iniciar sesión como Cliente
                  %li
                    %a{:href => new_provider_session_path}
                      %span.h5.btn Iniciar sesión como Cuidador
            %li
              = link_to 'Registrarme', new_user_registration_path, class: "not-underline text-header "
            %li.active
              = link_to 'Quiero ser cuidador', new_provider_registration_path, class: "btn not-underline sign-up"